### ISSUE TITLE
[enhancement] allow implementing cutrom matching

### ISSUE THREAD

**Issue by scorpp** [TheSharpieOne/angular-validation-match#23]
it would be really nice to allow different types of matching to be implemented - e.g. one field less then another, end date after start date, etc.
a factory could be provided which accepts a matching function and returns new directive definition
client code could look like

```javascript
app.config(function(inputMatchFactory) {
  app.directive('endDateAfterStartDate', inputMatchFactory(function(myVal, otherVal){
    return myVal.getTime() > otherVal.getTime();
  })
})
```

**Comment by TheSharpieOne** [comment]
Thats not really "matching" and is outside of the scope of this directive.  That would be more of a "compare".  While "matching" is "comparing", "comparing" is not necessarily "matching" (matching is a subset of comparing).

I could probably create a new project with a directive called `compare` that would allow you to do that.  It would end up being very similar to this project with that enhancement.  Technically, you would be able to perform match comparisons with that as well as what you described above.  While using a factory to create the specific directives, I imagine it would also (in addition to the factory) allow passing in the compare function with each element so that one would be able to create the compare functions on the fly.

I'm going to keep this open until I have time to at least start the new "angular-input-compare" project.

**Comment by TheSharpieOne** [comment]
Yeah, probably no time to really make this and since this issue was just a reminder to create the new project/repo for that... I'm going to close the issue.
