### ISSUE TITLE
Match validation requires ngModel to be on the element

### ISSUE THREAD

**Issue by mightydes** [TheSharpieOne/angular-validation-match#34]
When plugin used with [ui bootstrap typeahead](http://angular-ui.github.io/bootstrap/versioned-docs/0.13.4/#/typeahead)
occures warning: `Match validation requires ngModel to be on the element`.

Check [example](http://plnkr.co/edit/tDHIBSpAaN2RoftqVeGI?p=preview) (ui.bootstrap#0.13.4, validation.match#1.5.2)

**Comment by TheSharpieOne** [comment]
The angular UI loves to gobble up all of the common directive names.  Since angular-ui bootstrap in it's whole is so massive (in terms of the attribute names they consume)... they should prefix all of their attributes, but they don't.

I can
A: Make that warning go away and just silently ignore elements which contain `match` and have no `ngModel`.
B: prefix [all] the attributes to not collide. (In this case I would need a nice prefix that is both meaningful and not a burden)
C: Add another directive, and only read the attributes when that directive is present (similar to what angular-ui bootstrap is doing, which means it runs into the same issues if someone else creates directives with the same name as the attributes used by the match directive)

**Comment by mightydes** [comment]
I suppose to bump version to 1.5.3 with silent ignore for now, and add prefix in later release.
You can use `vd-` prefix, for example.
Also, you are right about the possible conflicts, but `match` is really common attribute.

**Comment by TheSharpieOne** [comment]
Removed the warning and published the release (npm and bower).  You should be good now.
Did a full minor version update (1.6.0 -> 1.7.0) since I also cleaned up a few things since it has been so long since this project had some TLC.

**Comment by mightydes** [comment]
Bravo!
